CRUD_Basic/articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/edit/', views.edit, name="edit"),
    path('<int:pk>/update/', views.update, name="update"),
]

CRUD_Basic/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

CRUD_Basic/articles/views.py
from multiprocessing import context
from turtle import title
from django.shortcuts import render, redirect
import articles
from articles.models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:index')

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

CRUD_Basic/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h1>{{article.pk}}번째 글</h1>
  <hr>
  <p>제목: {{article.title}}</p>
  <p>내용: {{article.content}}</p>
  <p>작성 시간: {{article.created_at}}</p>
  <p>수정 시각: {{article.updated_at}}</p>
  <hr>
  
  <a href="{% url 'articles:edit' article.pk %}">EDIT</a><br>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value = "DELETE">
  </form>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}

CRUD_Basic/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>EDIT</h1>
<form action="{% url 'articles:update' article.pk %}" method = 'POST'>
  {% csrf_token %}
  <label for="title">Title:</label>
  <input type="text" id="title" name="title" value="{{article.title}}"><br>

  <label for="content">Content:</label>
  <textarea type="text" id="content" name="content">{{article.content}}</textarea><br>
  <input type="submit" value="Submit">
  <hr>
</form>
<a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}

CRUD_Basic/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Articles</h1>
  <a href="{% url 'articles:new' %}">NEW</a>
  <hr>
  {% for article in articles %}
    <h3>글 번호: {{article.pk}}</h3>
    <h3>글 제목: {{article.title}}</h3>
    <h3>글 내용: {{article.content}}</h3>
    <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
    <hr>
  {% endfor %}
{% endblock content %}

CRUD_Basic/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
<h1>NEW</h1>
<form action="{% url 'articles:create' %}" method='POST'>
  {% csrf_token %}
  <label for='title'>Title:</label>
  <input type="text" id="title" name="title"><br>
  <label for="content">Content:</label>
  <textarea type="text" id="content" name="content"></textarea><br>
  <input type="submit" value='Submit'>
</form>
<hr>
<a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}