Onsil_django_05/chattings/urls.py
from django.urls import path
from . import views

app_name = 'chattings'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
]

Onsil_django_05/project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chattings/', include('chattings.urls')),
]

Onsil_django_05/chattings/models.py
from django.db import models

# Create your models here.
class Chat(models.Model):
    user = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Onsil_django_05/chattings/forms.py
from django import forms
from .models import Chat

class ChatForm(forms.ModelForm):
    user = forms.CharField(
        label='작성자',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nickname',
                'maxlength': 10,
            }
        )
    )

    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Chat!',
                'rows': 5,
                'cols': 50,
            }
        ),
        error_messages={
            'required': 'Please enter your content',
        }
    )

    class Meta:
        model = Chat
        fields = '__all__'

Onsil_django_05/chattings/views.py
from django.shortcuts import render, redirect
from .models import Chat
from .forms import ChatForm


# Create your views here.
def index(request):
    # DB에 전체 데이터를 조회
    chattings = Chat.objects.all()
    context = {
        'chattings': chattings,
    }
    return render(request, 'chattings/index.html', context)


def create(request):
    if request.method == 'POST':
        # create
        form = ChatForm(request.POST)
        if form.is_valid():
            chat = form.save()
            return redirect('chattings:detail', chat.pk)
    else:
        # new
        form = ChatForm()
    context = {
        'form': form,
    }
    return render(request, 'chattings/create.html', context)

def detail(request, pk):
    # variable routing으로 받은 pk 값으로 데이터를 조회
    chat = Chat.objects.get(pk=pk)
    context = {
        'chat': chat
    }
    return render(request, 'chattings/detail.html', context)

Onsil_django_05/chattings/templates/chattings/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'chattings:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
  </form>
  <hr>
  <a href="{% url 'chattings:index' %}" class="text-decoration-none">[back]</a>
{% endblock content %}

Onsil_django_05/chattings/templates/chattings/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h2>{{ chat.pk }}번째 글</h2>
  <hr>
  <p>작성자 : {{ chat.user }}</p>
  <p>내용 : {{ chat.content }}</p>
  <p>작성 시각 : {{ chat.created_at }}</p>
  <p>수정 시각 : {{ chat.updated_at }}</p>
  <hr>
  <a href={% url 'chattings:index' %} class="text-decoration-none">[back]</a>
{% endblock content %}

Onsil_django_05/chattings/templates/chattings/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Chattings</h1>
  <a href="{% url 'chattings:create' %}" class="text-decoration-none">CREATE</a>
  <hr>
  {% for chat in chattings %}
    <p>글 번호 : {{ chat.pk }}</p>
    <p>작성자 : {{ chat.user }}</p>
    <p>글 내용 : {{ chat.content }}</p>
    <a href="{% url 'chattings:detail' chat.pk %}" class="text-decoration-none">[detail]</a>
    <hr>
  {% endfor %}
{% endblock content %}